### ISSUE TITLE
email в чеках

### ISSUE THREAD

**Issue by M1XAJIbI4** [tinkoff-mobile-tech/tinkoff-asdk-ios#458]
Если есть чек, но в нём нет телефона или емейла. То при установке флага обязательный емейл, при его вводе на экране реквизитов карты, ничего не сработает -  оплата не пройдёт так как при передаче чека там обязательно нужен емейл! Нельзя ли сделать так что если в чеке нет емейла, то подставлять его с этого экрана где пользователь обязан будет его ввести?

**Comment by ivanglushko** [comment]
Привет! Подскажи на какой версии сдк такое поведение ловите?

**Comment by M1XAJIbI4** [comment]
В последней 3.1.0

**Comment by ivanglushko** [comment]
Привет еще раз, в итоге да такая проблема есть, завел задачу по ней [EACQAPW-5527](https://jira.tcsbank.ru/browse/EACQAPW-5527), будем разбираться. 
Буду в дальнейшем тут информировать о статусе.

**Comment by ivanglushko** [comment]
Если в итоге мы будем подставлять email введеный в шторке, мы также настоятельно советуем иметь о клиенте информацию телефон или почту (требования НСПК для проведения оплаты) ибо юзер может ее не ввести в шторке поле опциональное

**Comment by ivanglushko** [comment]
Привет!
После обсуждения с командой и руководством пришли к такому выводу:

> Поле с email действительно является необходимым и сбор этих данных происходит на стороне приложения партнера. Наша платежная шторка не собирает email пользователей для отправки чека. Поле, которое отображается в интерфейсе, используется для сбора email-а для отправки квитанций с информацией об оплате заказа.  Отправка квитанций является опциональной для покупателя - он может не вводить почту. Поэтому, чтобы платеж не отбивался ошибкой, вам необходимо на своей стороне реализовать сбор email пользователей и передавать эти данные вместе с информацией о заказе.
