### ISSUE TITLE
ФФД 1.2

### ISSUE THREAD

**Issue by tikhomirov-dev** [tinkoff-mobile-tech/tinkoff-asdk-ios#490]
### Описание бага
> Отсутствует возможность использования ФФД 1.2 при формировании чека

### После каких действий возникает ошибка
> Читаем [документацию](https://tinkoff.github.io/api_asdk/#tag/Metody-priema-platezhej/paths/~1Init/post), видим два варианта структуры чека, и поле **FfdVersion**

### Ожидаемое поведение
> Есть возможность заполнить чек с FfdVersion 1.2

### Что происходит на деле
> Возможность в ASDK отсутствует

**Comment by ivanglushko** [comment]
Привет!  Спасибо за обращение.
Да сейчас нет возможности в асдк передавать этот параметр. 
Пока разбираемся на своей стороне, критичность и анализ проблемы 🤔
Чуть позже дадим полноценный ответ.

**Comment by ivanglushko** [comment]
Привет, в итоге ваш вопрос пришел к нам в канал поддержки, там им и занимаемся. 
Создали задачу AS-13775. 
Остальные апдейты и вопросы через поддержку.
