### ISSUE TITLE
Проведение платежей с использованием своего UI

### ISSUE THREAD

**Issue by rmurad93** [tinkoff-mobile-tech/tinkoff-asdk-ios#492]
Спасибо большое что предоставили возможность использовать свой UI для проведения платежа.

Можете пожалуйста:
1. Сделать более подробное описание как использовать. Желательно с примером
2. Добавить возможность использовать СБП со своим результирующим экраном

**Comment by ivanglushko** [comment]
#### Привет, Мурад!

1. Тут врядли будет документация ибо все аспекты покрыть будет сложно. 
    - Вместо этого советую исследовать наши апи и пояснения к ним - [Тут наша документация команды ASDK](https://tinkoff.github.io/api_asdk/) А вот [публичная документация АПИ методов](https://www.tinkoff.ru/kassa/develop/api/payments/) (на нее мы ориентируемся в 1 очередь)
    - Смотреть сурс код Core модуля и его взаимодействие с UI модулем, публичные методы кор части имеют документацию кода.
    - Исследовать наш сурс код [семпл приложения](https://github.com/tinkoff-mobile-tech/tinkoff-asdk-ios/tree/master/ASDKSample). Для быстрого запуска можно запустить команду `$ make start` (но нужен отдельный доступ до тест стенда чтобы запросы не отбивались ошибкой можно запросить у нашей поддержки)
 2. В **issues** мы в основном реагируем на баги. 
      - По поводу доработок и изменений коробочного решения следует обращаться в поддержку через персонального менеджера. Такие изменения сначала должны пройти цикл прежде чем попадут в разработку (если попадут). 
      - Всегда можно сделать форк нашего репозитория и внести свои правки, единственное поддержка кода и последующие обновления с основным репозиториям перекладываются на вас в таком случае.
